version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: charbelkallas
      MYSQL_DATABASE: recordings
      MYSQL_USER: charbelkallas
      MYSQL_PASSWORD: charbelkallas

  app:
    container_name: go-crud
    build: .
    depends_on:
      - mysql
    environment:
      DB_USERNAME: charbelkallas
      DB_PASSWORD: charbelkallas
      DB_DATABASE: recordings
      DATABASE_ADDR: mysql:3306
